import './globals.css'
import {Navbar} from "@/app/components/Navbar";
import {ProfilePic} from "@/app/components/ProfilePic";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <ProfilePic />
        {children}
      </body>
    </html>
  )
}
